name: shm

services:
  app:
    image: ghcr.io/btouchard/shm:latest
    container_name: shm-app
    depends_on:
      db:
        condition: service_healthy
    environment:
      SHM_DB_DSN: "postgres://user:password@db:5432/metrics?sslmode=disable"
      PORT: "8080"
    ports:
      - "8080:8080"

  db:
    image: postgres:15-alpine
    container_name: shm-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: metrics
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d metrics"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: